"use client";

// AUTO-GENERATED by scripts/backfill_seo_engagement.py.
// Renders <SeoPageReactions> and <SeoPageComments> from @m13v/seo-components
// at the bottom of every SEO page (route prefixes below). Returns null on
// non-SEO routes so the homepage / pricing / etc. stay clean.

import { usePathname } from "next/navigation";
import { SeoPageComments, SeoPageReactions } from "@seo/components";

const API = process.env.NEXT_PUBLIC_AUTOPOSTER_API || "https://s4l.ai";
const SITE = "t8r.tech";
const SEO_PREFIXES: string[] = ["/t/", "/alternative/", "/use-case/", "/best/", "/blog/", "/guides/"];

export function SeoEngagement() {
  const pathname = usePathname() || "";
  const onSeoRoute = SEO_PREFIXES.some((p) => pathname.startsWith(p));
  if (!onSeoRoute) return null;
  return (
    <>
      <SeoPageReactions site={SITE} pageSlug={pathname} apiOrigin={API} />
      <SeoPageComments site={SITE} pageSlug={pathname} apiOrigin={API} />
    </>
  );
}
