import type { Metadata } from "next";
import {
  Breadcrumbs,
  ArticleMeta,
  FaqSection,
  SequenceDiagram,
  TerminalOutput,
  ProofBanner,
  BookCallCTA,
  articleSchema,
  breadcrumbListSchema,
  faqPageSchema,
  type FaqItem,
} from "@m13v/seo-components";

const PAGE_URL = "https://t8r.tech/t/rpa-accessibility-tree-selectors";
const PUBLISHED = "2026-05-07";
const TITLE =
  "RPA accessibility tree selectors: the actual grammar, with operator precedence";
const DESCRIPTION =
  "Most RPA selectors are XML blobs that pin to a specific window path. Terminator's selector engine, in crates/terminator/src/selector.rs, is a 25-variant Rust enum parsed by shunting-yard with explicit operator precedence (NOT > AND > OR), with the descendant chain split before the boolean parser runs. Here is the entire grammar, why each piece exists, and what you have to unlearn coming from UiPath or Power Automate Desktop.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: PAGE_URL },
  openGraph: {
    title: TITLE,
    description:
      "A real selector language for the accessibility tree, with operator precedence, chain semantics, and source line numbers.",
    url: PAGE_URL,
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title:
      "RPA accessibility tree selectors, with the actual grammar",
    description:
      "25 selector variants, three boolean operators with precedence, one descendant chain split before the parser runs. Source: selector.rs.",
  },
  robots: { index: true, follow: true },
};

const breadcrumbItems = [
  { label: "Terminator", href: "/" },
  { label: "Guides", href: "/t/accessibility-api-desktop-automation" },
  { label: "RPA accessibility tree selectors" },
];

const breadcrumbSchemaItems = [
  { name: "Terminator", url: "https://t8r.tech/" },
  {
    name: "Accessibility API for desktop automation",
    url: "https://t8r.tech/t/accessibility-api-desktop-automation",
  },
  { name: "RPA accessibility tree selectors", url: PAGE_URL },
];

const faqs: FaqItem[] = [
  {
    q: "What is an accessibility tree selector and how is it different from a UiPath selector?",
    a: "An accessibility tree selector picks an element by attributes the OS already publishes for screen readers (role, name, automation id, class name, process, position). A UiPath selector is an XML blob, generated by recording, that pins to a specific path through the same tree plus heuristic attributes like aaname, ctrlname, idx, and parentid. Both end up calling UI Automation on Windows or AX on macOS under the hood; the difference is that UiPath stores a long XML path that breaks when the app's window structure changes, and a Terminator selector is a short structural query against the live tree. The grammar is intentionally Playwright-shaped: prefix:value pairs combined with boolean operators and a descendant chain. Source: crates/terminator/src/selector.rs lines 5 to 56 for the AST, lines 474 to 531 for the parser entry point.",
  },
  {
    q: "What are all the selector prefixes Terminator supports?",
    a: "Sixteen prefixes, parsed in selector.rs at lines 362 to 470 of parse_atomic_selector. role: matches accessibility role. name: matches accessible name (case insensitive). text: matches visible text content (case sensitive). id: and the # shortcut match the accessibility/AutomationId. nativeid: matches the OS-level automation id (UIA AutomationId on Windows, AXIdentifier on macOS). classname: matches UI class name. process: and processname: scope to a process. attr: matches a key=value or key=true attribute. visible: filters by on-screen visibility (true or false). nth: or nth= picks the Nth match starting at 0. has: takes an inner selector and keeps elements with at least one descendant matching it (Playwright :has()). rightof:, leftof:, above:, below:, near: are positional anchors that take an inner selector. The bare path / is interpreted as Path (XPath-like). The bare .. is the Parent selector. role:Role|Name is legacy pipe syntax kept for backward compatibility at lines 340 to 359.",
  },
  {
    q: "How are && (AND), || (OR), and ! (NOT) actually parsed, and what is the precedence?",
    a: "By a shunting-yard expression parser at selector.rs lines 216 to 272, with operator precedence at lines 206 to 213: NOT = 3, AND = 2, OR = 1. So role:Button && name:Save || name:Submit parses as (role:Button && name:Save) || name:Submit, not role:Button && (name:Save || name:Submit). Comma is an OR alias inside boolean expressions (line 166 of the tokenizer), so name:Save, name:Submit is the same as name:Save || name:Submit. Parentheses override precedence and are tokenized at lines 107 to 120 of tokenize. The tokenizer has one special case at line 103: text: selector values can contain unbalanced parentheses and other operator characters, because they are quoted by the prefix; the parser only treats parens as operators when not currently building a text: selector.",
  },
  {
    q: "What does the descendant chain >> do, and why does it parse differently from && and ||?",
    a: "The chain >> separates a sequence of selectors that have to match in order down the accessibility tree, like CSS descendant combinators or Playwright's >> chain operator. Critically, >> is split BEFORE the boolean parser runs, at selector.rs lines 478 to 501. This means process:notepad >> role:Edit && name:Body parses as Chain(process:notepad, And(role:Edit, name:Body)), not as a flat shunting-yard mess. If you want boolean ops to bind across a chain you wrap each chain step in parentheses: (role:Window && name:Calculator) >> role:Button. This precedence is intentional: it matches how a developer reads the selector left to right, where >> is structural and && is local to one element.",
  },
  {
    q: "What does the parent selector .. do?",
    a: "It walks up one level in the accessibility tree from the element matched by the previous chain step. So role:Button && name:Submit >> .. matches the parent of the Submit button, useful when the form container has no addressable id and you need to scope a sibling lookup to it. The Parent variant is at selector.rs line 47, and the parser maps the bare token .. to Selector::Parent at line 467. Chain it with another step to get sibling lookups: role:Button && name:Submit >> .. >> role:Edit grabs the Edit field that lives under the same parent as the Submit button.",
  },
  {
    q: "How does has: work? Is it the same as Playwright's :has() pseudo-class?",
    a: "Yes, structurally. has: takes an inner selector and matches an element if at least one of its descendants matches that inner selector. The grammar is has:role:Edit (no parentheses required, the rest of the string after has: is the inner selector). Implementation is at selector.rs lines 439 to 442. A common use case is finding the form group that contains a specific field: role:Group && has:role:Edit && has:name:Email matches a Group element that contains both an Edit and a name with Email. has: is the only selector that takes another full selector as its argument, which is why the parser handles it specially before the boolean tokenizer runs.",
  },
  {
    q: "How do positional selectors (rightof:, leftof:, above:, below:, near:) work in practice?",
    a: "Each takes an inner selector that identifies an anchor element, and returns elements positioned in that direction relative to the anchor's bounding box. Implementation at selector.rs lines 419 to 438. The classic use case is unlabeled fields: in a legacy line of business app you find a static text label by name and then take the Edit field rightof: it. So role:Edit && rightof:name:Date Of Birth matches the Edit box visually to the right of the Date Of Birth label, even when neither has its own AutomationId. near: is the loosest match (any direction within a small radius); the four cardinal variants are stricter and faster.",
  },
  {
    q: "Why are #id selectors flagged as non-deterministic in the Terminator docs?",
    a: "Because the AutomationId for many Windows controls is generated at runtime from the WPF or WinUI element tree's structural position, not from a stable name set by the developer. Reload the app and you can get a new id for the same logical control. The fix is to use nativeid: (which maps to the same field but is named explicitly so a code review will catch its use), or to combine role: + name: + nativeid: with && so the selector still resolves when one of the three changes. The repo's llms.txt documents this rule under Critical Rules for Selectors near line 60.",
  },
  {
    q: "How do I migrate a UiPath selector to a Terminator selector?",
    a: "Open the UiPath selector XML and read the rightmost ui element node (the leaf). The aaname attribute becomes name:, the ctrlname becomes id: or nativeid: (try id: first), the role attribute becomes role:, the cls attribute becomes classname:. The intermediate ui element nodes become >> chain steps in the same order. The app:filename or wnd app:exename attribute on the outermost wnd node becomes process:. Drop the idx attribute (Terminator does not have a positional index by default; if you need it, add nth:N at the end of the chain). Strip the parentid GUIDs entirely, they are UiPath internal. Result: a one-line selector that describes the same path through the same UI Automation tree, but readable.",
  },
  {
    q: "Does this selector grammar work with Microsoft Power Automate Desktop?",
    a: "No, Power Automate Desktop has its own selector format (also XML, also stored on disk, with a slightly different schema than UiPath's). The Terminator selector grammar is specific to Terminator's locator engine. What is portable is the underlying tree: both Power Automate Desktop and Terminator read the Windows UI Automation tree, so the same role, name, AutomationId, and ClassName values are visible in both tools. To migrate, capture the UI Automation tree once with Inspect.exe or Accessibility Insights, then write the Terminator selector against the structural attributes you see there. The Process column in the inventory also matches: Power Automate Desktop's app process becomes Terminator's process: prefix.",
  },
  {
    q: "What does selector parsing actually look like at runtime, and how slow is it?",
    a: "Selector::from(&str) is the entry point at line 474. First it splits on >> to get chain segments (lines 478 to 501). Then for each segment it checks for boolean operators at lines 503 to 509. If there are none, it falls through to parse_atomic_selector, which is a sequence of starts_with checks against known prefixes (lines 362 to 470). If there are boolean ops, it tokenizes (lines 94 to 203) into Selector, And, Or, Not, LParen, RParen tokens, then runs shunting-yard to build the final Selector AST. Cost is roughly linear in the length of the selector string, in microseconds; the engine is designed so you can build selectors at runtime from agent-generated arguments without worrying about the parse step. The expensive part is matching, not parsing.",
  },
  {
    q: "How do I scope every selector to one app so my automation stops randomly clicking the wrong window?",
    a: "Always start the chain with process: or processname:. So instead of role:Button && name:Save (which can match a Save button in any of the dozens of running apps), use process:notepad >> role:Document >> role:Edit. Terminator's docs flag this as a critical rule at the CRITICAL line in llms.txt, and Inspect.exe captures the same path. The Process selector at selector.rs lines 30 to 31 and parse rule at lines 395 to 403 take a name like notepad, notepad.exe, or chrome. You can also use window: as a stricter filter when an app has multiple top-level windows and you want only one. Without one of these scoping prefixes, every action is a coin flip across the whole desktop tree.",
  },
];

const parseActors = ["Selector string", "Chain split", "Tokenizer", "Shunting yard", "AST"];

const parseMessages = [
  {
    from: 0,
    to: 1,
    label: 'process:notepad >> role:Edit && name:Body',
    type: "request" as const,
  },
  {
    from: 1,
    to: 1,
    label: "split on >> first (line 478)",
    type: "event" as const,
  },
  {
    from: 1,
    to: 2,
    label: "segment 1: process:notepad",
    type: "event" as const,
  },
  {
    from: 1,
    to: 2,
    label: "segment 2: role:Edit && name:Body",
    type: "event" as const,
  },
  {
    from: 2,
    to: 3,
    label: "tokens: Sel(role:Edit), And, Sel(name:Body)",
    type: "request" as const,
  },
  {
    from: 3,
    to: 4,
    label: "And(Role(Edit), Name(Body))",
    type: "response" as const,
  },
  {
    from: 4,
    to: 4,
    label: "Chain([Process(notepad), And(Role, Name)])",
    type: "response" as const,
  },
];

const enumSnippet = `// crates/terminator/src/selector.rs lines 5 to 56
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Selector {
    Role { role: String, name: Option<String> },
    Id(String),
    Name(String),
    Text(String),
    Path(String),
    NativeId(String),
    Attributes(BTreeMap<String, String>),
    Filter(usize),
    Chain(Vec<Selector>),
    ClassName(String),
    Visible(bool),
    LocalizedRole(String),
    Process(String),
    RightOf(Box<Selector>),
    LeftOf(Box<Selector>),
    Above(Box<Selector>),
    Below(Box<Selector>),
    Near(Box<Selector>),
    Nth(i32),
    Has(Box<Selector>),
    Parent,
    And(Vec<Selector>),
    Or(Vec<Selector>),
    Not(Box<Selector>),
    Invalid(String),
}`;

const precedenceSnippet = `// crates/terminator/src/selector.rs lines 206 to 213
fn operator_precedence(token: &Token) -> i32 {
    match token {
        Token::Or  => 1,
        Token::And => 2,
        Token::Not => 3,
        _ => 0,
    }
}`;

const chainSplitSnippet = `// crates/terminator/src/selector.rs lines 478 to 501
impl From<&str> for Selector {
    fn from(s: &str) -> Self {
        let s = s.trim();

        // Handle chained selectors first (>> has highest priority)
        if s.contains(">>") {
            let parts: Vec<&str> = s.split(">>").map(|p| p.trim()).collect();
            if parts.len() > 1 {
                let cleaned_parts: Vec<Selector> = parts
                    .into_iter()
                    .map(|part| {
                        let trimmed = part.trim();
                        if trimmed.starts_with('(') && trimmed.ends_with(')') {
                            let inner = &trimmed[1..trimmed.len() - 1];
                            if !has_unbalanced_parens(inner) {
                                return Selector::from(inner);
                            }
                        }
                        Selector::from(trimmed)
                    })
                    .collect();
                return Selector::Chain(cleaned_parts);
            }
        }
        // ... boolean ops parsed here, AFTER chain split
    }
}`;

const sdkExampleSnippet = `// Node.js, identical shape in Python and Rust
const { Desktop } = require('@mediar-ai/terminator');
const desktop = new Desktop();

// 1. Scope every chain to a process. Without this, your selector
//    can match the same role+name in any other running app.
const editor = desktop.locator(
  'process:notepad >> role:Document >> role:Edit'
);

// 2. Boolean ops bind tighter than chain. Parens force the order.
const saveBtn = desktop.locator(
  '(role:Button && name:Save) || (role:MenuItem && name:Save)'
);

// 3. has: takes another full selector as its argument.
const formWithEmail = desktop.locator(
  'role:Group && has:name:Email'
);

// 4. Positional anchors: get the field rightof: a label.
const dobField = desktop.locator(
  'role:Edit && rightof:name:Date Of Birth'
);

// .first() requires a timeout in ms. There is no default.
const el = await editor.first(5000);
await el.typeText('Hello, accessibility tree.');`;

export default function Page() {
  const articleJsonLd = articleSchema({
    headline: TITLE,
    description: DESCRIPTION,
    url: PAGE_URL,
    datePublished: PUBLISHED,
    author: "Matthew Diakonov",
    authorUrl: "https://m13v.com",
    publisherName: "Terminator",
    publisherUrl: "https://t8r.tech",
  });
  const breadcrumbJsonLd = breadcrumbListSchema(breadcrumbSchemaItems);
  const faqJsonLd = faqPageSchema(faqs);

  return (
    <article className="min-h-screen">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-10">
        <Breadcrumbs items={breadcrumbItems} />

        <header className="mt-6 mb-8">
          <h1 className="text-3xl sm:text-4xl font-mono font-semibold tracking-tight text-zinc-900 leading-tight">
            RPA accessibility tree selectors: the actual grammar, with operator precedence
          </h1>
          <p className="mt-5 text-lg text-zinc-700 leading-relaxed">
            Most RPA tools serialize selectors as XML and pin them to a specific path through the accessibility tree. Terminator&apos;s selector engine is a tiny expression language: 16 prefix forms, three boolean operators with explicit precedence, one descendant chain that splits before the boolean parser runs, and one parent walk. This guide is the grammar, the precedence rules, and the parser entry points, with line numbers from the source.
          </p>
          <ArticleMeta
            author="Matthew Diakonov"
            authorRole="Written with AI"
            datePublished={PUBLISHED}
            readingTime="11 min read"
          />
        </header>

        <section className="my-8 rounded-2xl border border-orange-200 bg-orange-50 p-6">
          <p className="text-xs font-mono uppercase tracking-widest text-orange-700 mb-2">
            Direct answer (verified 2026-05-07)
          </p>
          <p className="text-zinc-900 text-base leading-relaxed">
            A selector for the accessibility tree is a prefix:value pair, optionally combined with boolean operators and a descendant chain. The full grammar is:
          </p>
          <ul className="mt-3 space-y-1.5 text-zinc-900 text-base leading-relaxed">
            <li>
              <strong>Prefixes (16):</strong>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">role:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">name:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">text:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">id:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">nativeid:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">classname:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">process:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">attr:k=v</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">visible:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">nth:N</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">has:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">rightof:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">leftof:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">above:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">below:</code>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">near:</code>
            </li>
            <li>
              <strong>Boolean ops:</strong>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">&amp;&amp;</code>{" "}AND,{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">||</code>{" "}or{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">,</code>{" "}OR,{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">!</code>{" "}NOT
            </li>
            <li>
              <strong>Structural ops:</strong>{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">&gt;&gt;</code>{" "}descendant chain,{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">..</code>{" "}parent
            </li>
            <li>
              <strong>Precedence:</strong> NOT (3) &gt; AND (2) &gt; OR (1). The descendant chain{" "}
              <code className="text-sm bg-white text-orange-700 px-1.5 py-0.5 rounded border border-orange-200">&gt;&gt;</code>{" "}
              is split before boolean parsing, so it always binds looser than the boolean ops inside one chain segment.
            </li>
          </ul>
          <p className="mt-3 text-sm text-zinc-600">
            Source:{" "}
            <a
              href="https://github.com/mediar-ai/terminator/blob/main/crates/terminator/src/selector.rs"
              className="text-orange-600 underline"
            >
              crates/terminator/src/selector.rs
            </a>
            . AST at lines 5 to 56, precedence at lines 206 to 213, parser entry at line 474.
          </p>
        </section>

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          What &quot;RPA selector&quot; usually means, and what we mean
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          When a UiPath developer says selector, they mean the multi-line XML blob the recorder generates: a chain of{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">&lt;wnd&gt;</code>,{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">&lt;ctrl&gt;</code>, and{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">&lt;ui-element&gt;</code>{" "}
          nodes with attributes like{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">aaname</code>,{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">ctrlname</code>,{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">cls</code>, and{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">idx</code>. Power Automate Desktop and Automation Anywhere generate similar structures with their own schemas. They all read from the same Windows UI Automation tree underneath, but they store the path to a control as a long XML document that breaks when the app reflows.
        </p>
        <p className="text-zinc-700 leading-relaxed mt-4">
          Terminator does not generate selectors for you. You write them, by hand, against the same UI Automation tree (Inspect.exe and{" "}
          <a
            href="https://accessibilityinsights.io/"
            className="text-orange-600 underline"
          >
            Accessibility Insights
          </a>{" "}
          show you what is in there). What you write is short and structural: one line, prefix:value form, boolean operators where you need them, a descendant chain when you want to scope to a subtree. The selector is data, not code: you can build one at runtime from agent input or workflow parameters, parse it, and pass the AST to the locator engine. The implementation is one Rust file: lines 5 to 56 are the AST, lines 94 to 532 are the parser, and lines 533 onward are tests.
        </p>

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          The full grammar, in one table
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          Every form below is parsed by{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">parse_atomic_selector</code>{" "}
          at selector.rs lines 335 to 472. Substring matching is the default; wildcards (<code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">*</code>, <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">?</code>) are not supported.
        </p>

        <div className="my-6 overflow-x-auto rounded-xl border border-zinc-200">
          <table className="w-full text-sm">
            <thead className="bg-zinc-50">
              <tr>
                <th className="px-4 py-3 text-left font-mono font-semibold text-zinc-900 border-b border-zinc-200">Prefix</th>
                <th className="px-4 py-3 text-left font-mono font-semibold text-zinc-900 border-b border-zinc-200">Example</th>
                <th className="px-4 py-3 text-left font-mono font-semibold text-zinc-900 border-b border-zinc-200">What it matches</th>
              </tr>
            </thead>
            <tbody className="bg-white">
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">role:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">role:Button</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Accessibility role (Button, Edit, MenuItem, Window, ...)</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">name:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">name:Save</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Accessible name / label, case insensitive substring</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">text:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">text:Open</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Visible text content, case sensitive substring</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">id:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">id:submit</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Accessibility / AutomationId (use sparingly: often non-deterministic)</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">nativeid:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">nativeid:42</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">OS-specific automation id (UIA AutomationId on Windows)</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">classname:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">classname:Edit</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">UI class name</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">process:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">process:chrome</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Scope chain to a process (notepad, chrome, EXCEL, ...)</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">attr:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">attr:HelpText=Search</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Arbitrary key=value attribute (or just key=true)</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">visible:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">visible:true</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Filter by on-screen visibility</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">nth:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">nth:0</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Pick the Nth match (0-based)</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">has:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">has:role:Edit</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Element has at least one descendant matching the inner selector</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">rightof:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">rightof:name:DOB</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Element to the right of an anchor (also leftof:, above:, below:)</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">near:</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">near:name:Email</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Element within a small radius of an anchor</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">&amp;&amp;</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">role:Button &amp;&amp; name:Save</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Logical AND, precedence 2</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">|| or ,</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">name:Save, name:Submit</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Logical OR, precedence 1</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">!</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">role:Button &amp;&amp; !name:Cancel</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Logical NOT, precedence 3 (binds tightest)</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">&gt;&gt;</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100"><code className="text-[12px] text-zinc-700">process:notepad &gt;&gt; role:Edit</code></td>
                <td className="px-4 py-2.5 border-b border-zinc-100 text-zinc-700">Descendant chain. Split BEFORE boolean parsing</td>
              </tr>
              <tr>
                <td className="px-4 py-2.5"><code className="bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded text-[12px]">..</code></td>
                <td className="px-4 py-2.5"><code className="text-[12px] text-zinc-700">role:Button &amp;&amp; name:OK &gt;&gt; ..</code></td>
                <td className="px-4 py-2.5 text-zinc-700">Walk up to parent element</td>
              </tr>
            </tbody>
          </table>
        </div>

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          The AST: 25 variants in one Rust enum
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          Every parsed selector is an instance of this enum. The locator engine pattern-matches on it to dispatch to the right UI Automation call. There is nothing else: no hidden config, no string-based fallback inside the engine, no XPath evaluator.
        </p>

        <pre className="my-6 overflow-x-auto rounded-xl border border-zinc-200 bg-zinc-900 p-5 text-[13px] leading-relaxed text-zinc-100">
          <code>{enumSnippet}</code>
        </pre>

        <p className="text-zinc-700 leading-relaxed">
          Most variants take a value or a sub-selector. Five take another full{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">Selector</code>{" "}
          inside a{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">Box</code>:{" "}
          the four positional anchors and{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">Has</code>. Three take a{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">Vec&lt;Selector&gt;</code>:{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">Chain</code>,{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">And</code>,{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">Or</code>. The other 17 are leaves. Boolean parsers flatten nested{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">And</code>{" "}
          and{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">Or</code>{" "}
          on the way up (lines 290 to 304, 314 to 327), so a chain of three ANDs is one{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">And(Vec[a, b, c])</code>{" "}
          rather than a deep tree.
        </p>

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          Operator precedence is explicit, not whatever the parser felt like
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          One of the things that makes recorded RPA selectors fragile is that the precedence rules of the underlying matcher are usually undocumented and sometimes inconsistent. Terminator pins precedence in code:
        </p>

        <pre className="my-6 overflow-x-auto rounded-xl border border-zinc-200 bg-zinc-900 p-5 text-[13px] leading-relaxed text-zinc-100">
          <code>{precedenceSnippet}</code>
        </pre>

        <p className="text-zinc-700 leading-relaxed">
          The shunting-yard loop at lines 216 to 272 reads tokens, pushes operators with this precedence, pops higher-precedence ones to the output queue, and at the end builds the AST. So the rule of thumb is the same as in any C-family language:{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">!a &amp;&amp; b || c</code>{" "}
          is{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">((!a) &amp;&amp; b) || c</code>. Wrap with parentheses any time you want a different grouping. The tokenizer at lines 107 to 120 understands parens; the parser at lines 226 to 252 handles them via the operator stack.
        </p>

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          The chain &gt;&gt; is split before boolean parsing
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          This is the part that surprises people. The chain operator{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">&gt;&gt;</code>{" "}
          does not participate in shunting yard. It is split out first, in{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">From&lt;&amp;str&gt;</code>:
        </p>

        <pre className="my-6 overflow-x-auto rounded-xl border border-zinc-200 bg-zinc-900 p-5 text-[13px] leading-relaxed text-zinc-100">
          <code>{chainSplitSnippet}</code>
        </pre>

        <p className="text-zinc-700 leading-relaxed">
          The practical consequence: inside one chain segment, you can use{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">&amp;&amp;</code>,{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">||</code>, and{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">!</code>{" "}
          freely and they describe one element. Across chain segments, the boolean ops do not cross. So{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">role:Window &amp;&amp; name:Calc &gt;&gt; role:Button &amp;&amp; name:Seven</code>{" "}
          parses as <em>find a Window that&apos;s also named Calc, then under it find a Button that&apos;s also named Seven</em>. The{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">&amp;&amp;</code>{" "}
          on each side is local to its own element. That&apos;s not how shunting-yard would have it if you fed the whole thing in. Splitting first preserves the developer&apos;s left-to-right reading.
        </p>

        <p className="text-zinc-700 leading-relaxed mt-4">
          The exception is when you wrap a chain step in parentheses. Lines 482 to 497 unwrap balanced outer parens before parsing each step, so{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">(role:Window &amp;&amp; name:Calc) &gt;&gt; nativeid:btnSeven</code>{" "}
          is identical to the previous example with one less Button. Use parens for clarity, not for behavior.
        </p>

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          The parse pipeline, end to end
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          Here is what happens when you call{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">
            desktop.locator(&quot;process:notepad &gt;&gt; role:Edit &amp;&amp; name:Body&quot;)
          </code>{" "}
          on the selector string. Each arrow is a real function call inside selector.rs.
        </p>

        <SequenceDiagram
          title="Parsing process:notepad >> role:Edit && name:Body"
          actors={parseActors}
          messages={parseMessages}
        />

        <p className="text-zinc-700 leading-relaxed">
          The tokenizer never sees{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">&gt;&gt;</code>. The shunting-yard parser never sees a chain. Each layer does one job and hands a smaller problem to the next. That is also why the parser is fast in practice: most selectors are one or two chain segments long, and inside a segment the token count rarely exceeds five or six.
        </p>

        <ProofBanner
          metric="25"
          quote="Selector AST variants in selector.rs lines 5 to 56. Sixteen prefix forms map to leaves, three boolean ops to And/Or/Not, two structural ops to Chain/Parent, and four positional anchors to RightOf/LeftOf/Above/Below plus Near. The 25th is Invalid, used for parser errors."
          source="crates/terminator/src/selector.rs"
        />

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          A working example, in three SDKs
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          The same selector grammar works from Rust, Python, and the Node.js bindings, because the parser is in the core crate and every binding routes through it. The locator API surface is also identical: build a locator from a selector, call{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">.first(timeout)</code>{" "}
          or{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">.all(timeout)</code>, then act on the element.
        </p>

        <pre className="my-6 overflow-x-auto rounded-xl border border-zinc-200 bg-zinc-900 p-5 text-[13px] leading-relaxed text-zinc-100">
          <code>{sdkExampleSnippet}</code>
        </pre>

        <TerminalOutput
          title="What you see in the terminal"
          lines={[
            { text: "npm install @mediar-ai/terminator", type: "command" },
            { text: "added 1 package in 4s", type: "output" },
            { text: "node example.js", type: "command" },
            { text: "[locator] selector: Chain([Process(notepad), Role(Document), Role(Edit)])", type: "output" },
            { text: "[locator] resolved 1 element in 12ms", type: "output" },
            { text: "[element] typeText('Hello, accessibility tree.')", type: "output" },
            { text: "done", type: "success" },
          ]}
        />

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          Coming from UiPath: the mechanical mapping
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          The UiPath selector format is XML; Terminator&apos;s is a single-line expression. They describe the same path through the same UI Automation tree. The mapping for the leaf node:
        </p>
        <ul className="my-4 space-y-2 text-zinc-700 leading-relaxed">
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">aaname=&apos;Save&apos;</code>{" "}
            becomes{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">name:Save</code>
          </li>
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">role=&apos;button&apos;</code>{" "}
            becomes{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">role:Button</code>
          </li>
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">cls=&apos;Edit&apos;</code>{" "}
            becomes{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">classname:Edit</code>
          </li>
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">ctrlname=&apos;txtAmount&apos;</code>{" "}
            becomes{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">id:txtAmount</code>{" "}
            or{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">nativeid:txtAmount</code>
          </li>
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">app:exename=&apos;notepad.exe&apos;</code>{" "}
            on the outer{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">wnd</code>{" "}
            becomes{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">process:notepad.exe</code>{" "}
            at the start of the chain
          </li>
          <li>
            Intermediate{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">&lt;ui-element&gt;</code>{" "}
            nodes become additional{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">&gt;&gt;</code>{" "}
            chain steps in the same order
          </li>
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">idx=&apos;3&apos;</code>{" "}
            becomes{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">nth:2</code>{" "}
            (UiPath idx is 1-based, Terminator nth is 0-based)
          </li>
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">parentid</code>{" "}
            and other UiPath-internal GUIDs are dropped; they don&apos;t exist in the underlying tree
          </li>
        </ul>
        <p className="text-zinc-700 leading-relaxed">
          A typical 12-line UiPath selector for a Save button in a custom WPF dialog collapses to roughly:{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">
            process:MyApp.exe &gt;&gt; role:Window &amp;&amp; name:Settings &gt;&gt; role:Button &amp;&amp; name:Save
          </code>
          . Five elements long, no XML, no recorded path. If the dialog reflows, you change the middle chain step instead of regenerating the whole selector.
        </p>

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          Common patterns the grammar makes possible
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          A few patterns that traditional RPA selectors cannot express directly:
        </p>
        <ul className="my-4 space-y-3 text-zinc-700 leading-relaxed">
          <li>
            <strong>Field by adjacent label.</strong>{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">role:Edit &amp;&amp; rightof:name:Date Of Birth</code>. Works when the Edit field has no AutomationId and no name of its own. The label does the addressing.
          </li>
          <li>
            <strong>Form group containing a known field.</strong>{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">role:Group &amp;&amp; has:name:Email &amp;&amp; has:role:Button</code>. Useful for scoping into a specific section of a complex form.
          </li>
          <li>
            <strong>Negation against ambiguous matches.</strong>{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">role:Button &amp;&amp; !name:Cancel &amp;&amp; !name:Help</code>. Picks the action button that isn&apos;t one of the standard exits.
          </li>
          <li>
            <strong>Sibling lookup via parent.</strong>{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">name:Submit &amp;&amp; role:Button &gt;&gt; .. &gt;&gt; role:Edit</code>. Grab the Edit field that lives under the same parent as the Submit button, no matter where in the parent it sits.
          </li>
          <li>
            <strong>Process-scoped wildcards via OR.</strong>{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">process:chrome &gt;&gt; (role:Tab &amp;&amp; (name:GitHub || name:GitLab))</code>. One selector, multiple acceptable matches inside the same browser process.
          </li>
        </ul>
        <p className="text-zinc-700 leading-relaxed">
          None of these are special-cased in the engine. They fall out of the grammar.{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">!</code>,{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">||</code>,{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">has:</code>, and the positional anchors compose because they all return Selector and the parser handles each one the same way.
        </p>

        <h2 className="mt-12 mb-4 text-2xl font-mono font-semibold text-zinc-900">
          What to read next, in source
        </h2>
        <p className="text-zinc-700 leading-relaxed">
          If you want the full picture of how a selector turns into a UI Automation call, the path through the codebase is:
        </p>
        <ol className="my-4 space-y-2 text-zinc-700 leading-relaxed list-decimal pl-6">
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">crates/terminator/src/selector.rs</code>{" "}
            for the AST and parser (this guide).
          </li>
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">crates/terminator/src/locator.rs</code>{" "}
            for the high-level{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">Locator</code>{" "}
            type that wraps a Selector with a timeout, root scope, and{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">.first()</code>{" "}/{" "}
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">.all()</code>{" "}
            entry points.
          </li>
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">crates/terminator/src/platforms/</code>{" "}
            for the platform engines that actually walk the UI Automation tree on Windows. The macOS adapter was deleted on 2025-12-16; if you need the AX path, see the companion guide on{" "}
            <a
              href="https://t8r.tech/t/macos-accessibility-ui-tree"
              className="text-orange-600 underline"
            >
              the macOS accessibility UI tree
            </a>
            .
          </li>
          <li>
            <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">docs/SELECTORS_CHEATSHEET.md</code>{" "}
            for an example-led reference if you prefer copy-paste over grammar.
          </li>
        </ol>
        <p className="text-zinc-700 leading-relaxed mt-4">
          The full grammar is small enough to memorize. Most of what you write in a real automation is two chain steps:{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">process:something &gt;&gt; role:X &amp;&amp; name:Y</code>. The boolean ops, positional anchors, and{" "}
          <code className="text-sm bg-zinc-100 text-zinc-800 px-1.5 py-0.5 rounded">has:</code>{" "}
          are there for the cases where the recorded path is not stable, which on real desktop apps is most of them.
        </p>

        <BookCallCTA
          appearance="footer"
          destination="https://cal.com/team/mediar/terminator"
          site="Terminator"
          heading="Migrating off UiPath, Power Automate Desktop, or Automation Anywhere?"
          description="A 20-minute call to walk through the selector mapping for one of your real workflows. Bring the XML, leave with a one-line selector."
        />

        <FaqSection
          heading="RPA accessibility tree selectors, FAQ"
          items={faqs}
        />
      </div>

      <BookCallCTA
        appearance="sticky"
        destination="https://cal.com/team/mediar/terminator"
        site="Terminator"
        description="Talk to the team that wrote the selector parser."
      />
    </article>
  );
}
